[package]
name = "delivery"
version = "0.0.1"
authors = ["Adam Jacob <adam@getchef.com>"]

[dependencies.docopt]

[dependencies.docopt_macros]

[dependencies.regex]

[dependencies.regex_macros]

[dependencies.log]

[dependencies.rustc-serialize]

[dependencies.term]

