[package]
name = "delivery"
version = "0.0.1"
authors = ["Adam Jacob <adam@getchef.com>"]

[lib]
name = "delivery"
path = "src/delivery/lib.rs"

[[bin]]
name = "delivery"

[[test]]
name = "lib"

[dependencies]
docopt = "*"
docopt_macros = "*"
regex = "*"
regex_macros = "*"
log = "*"
rustc-serialize = "*"
toml = "*"
time = "*"
uuid = "*"
term = "*"
