[package]
name = "delivery"
version = "0.0.1"
authors = ["Adam Jacob <adam@getchef.com>"]

[lib]
name = "delivery"
path = "src/delivery/lib.rs"

[[bin]]
name = "delivery"

[[test]]
name = "lib"

[dependencies]
docopt = "0.6.38"
docopt_macros = "*"
regex = "*"
regex_macros = "*"
log = "*"
env_logger = "*"
rustc-serialize = "*"
time = "*"
term = "*"
libc = "*"
toml = "*"
tempdir = "*"
hyper = "*"
uuid = "*"
mime = "*"

[profile.dev]
debug = false

[profile.test]
debug = false
