driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['..', '/home/vagrant/delivery-cli']

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  attributes:
    vagrant:
      this_key_exists_so_we_have_a_vagrant_key: true

platforms:
  - name: centos-6.7
    run_list: yum-epel::default
  - name: centos-7.2
    run_list: yum-epel::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  # The following (private) boxes are shared via Atlas and are only
  # available to users working for Chef. Sorry, it's about software licensing.
  #
  # Chef-internal users, you will need to:
  # 1.  Create an Atlas account:  https://atlas.hashicorp.com/
  # 2.  Ping the Release Services room with your Atlas account name
  #     to be added to the relevant team in Atlas,
  # 3.  Do `vagrant login` with your Atlas creds so that you can download
  #     the private boxes.
  #
   # The Mac OS X boxes are VMware only also. You can enable VMware Fusion
  # by activating the `.kitchen.vmware.yml` file with the `KITCHEN_LOCAL_YAML`
  # environment variable:
  #
  #   KITCHEN_LOCAL_YAML=.kitchen.vmware.yml kitchen converge chefdk-macosx-109
  #
  <% %w(
    10.9
    10.10
    10.11
  ).each do |mac_version| %>
  - name: macosx-<%= mac_version %>
    driver:
      box: chef/macosx-<%= mac_version %> # private
      synced_folders:
      - ['..', '/Users/vagrant/delivery-cli']
  <% end %>
  - name: windows-2012r2-standard
    driver:
      customize:
        memory: 4096
      box: chef/windows-server-2012r2-standard # private
      synced_folders:
      # We have to mount this repos enclosing folder as the Omnibus build
      # gets cranky if the mounted ChefDK source folder is a symlink. This
      # mounts at `C:\vagrant\code` and the ChefDK source folder is available
      # at `C:\vagrant\code\chef-dk`
      - ['../..', '/vagrant/code']

suites:
  - name: delivery-cli
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/delivery-cli
    run_list:
      - omnibus::default
